package io.opendata.db.meta

import io.opendata.db.model.DbKind
import java.sql.Connection

/**
 * Генерация DDL (ТЗ 21): table, view, index, sequence, function, schema (+ type, trigger, constraint для PostgreSQL).
 * PostgreSQL/Cloudberry — функции pg_catalog (pg_get_*def), ClickHouse — SHOW CREATE, Dremio — INFORMATION_SCHEMA.
 */
class DdlGenerator(private val c: Connection, private val kind: DbKind) {
    private val loader = MetadataLoader(c, kind)
    private fun q(s: String) = loader.quote(s)

    fun ddl(o: DbObject): String = when {
        kind.isPostgresFamily -> postgres(o)
        kind == DbKind.CLICKHOUSE -> clickhouse(o)
        else -> dremio(o)
    }.trimEnd().let { if (it.endsWith(";")) it else "$it;" }

    // ----------------------------------------------------------------------------- PostgreSQL / Cloudberry

    private fun reg(o: DbObject) = "${q(o.schema ?: "public")}.${q(o.table ?: o.name)}"

    private fun one(sql: String, vararg p: String?): String? = c.prepareStatement(sql).use { ps ->
        p.forEachIndexed { i, v -> ps.setString(i + 1, v) }
        ps.executeQuery().use { rs -> if (rs.next()) rs.getString(1) else null }
    }

    private fun all(sql: String, vararg p: String?): List<String> = c.prepareStatement(sql).use { ps ->
        p.forEachIndexed { i, v -> ps.setString(i + 1, v) }
        ps.executeQuery().use { rs -> buildList { while (rs.next()) add(rs.getString(1)) } }
    }

    private fun postgres(o: DbObject): String = when (o.kind) {
        DbObjectKind.SCHEMA -> "CREATE SCHEMA ${q(o.name)}"
        DbObjectKind.TABLE -> pgTable(o)
        DbObjectKind.VIEW -> {
            val relkind = one("SELECT relkind::text FROM pg_class WHERE oid = to_regclass(?)", reg(o))
            val def = one("SELECT pg_get_viewdef(to_regclass(?), true)", reg(o)) ?: ""
            if (relkind == "m") "CREATE MATERIALIZED VIEW ${reg(o)} AS\n$def" else "CREATE OR REPLACE VIEW ${reg(o)} AS\n$def"
        }
        DbObjectKind.FUNCTION -> all(
            "SELECT pg_get_functiondef(p.oid) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace " +
                "WHERE n.nspname = ? AND p.proname = ? AND p.prokind IN ('f','p') ORDER BY p.oid", o.schema, o.name,
        ).joinToString(";\n\n") { it.trimEnd() }.ifEmpty { "-- функция ${o.name} не найдена" }
        DbObjectKind.SEQUENCE -> one(
            "SELECT format('CREATE SEQUENCE %I.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s%s', " +
                "schemaname, sequencename, data_type, increment_by, min_value, max_value, start_value, cache_size, " +
                "CASE WHEN cycle THEN ' CYCLE' ELSE '' END) FROM pg_sequences WHERE schemaname = ? AND sequencename = ?",
            o.schema, o.name,
        ) ?: "-- последовательность ${o.name} не найдена"
        DbObjectKind.TYPE -> pgType(o)
        DbObjectKind.INDEX -> one("SELECT pg_get_indexdef(to_regclass(?))", "${q(o.schema ?: "public")}.${q(o.name)}")
            ?: "-- индекс ${o.name} не найден"
        DbObjectKind.TRIGGER -> one(
            "SELECT pg_get_triggerdef(t.oid, true) FROM pg_trigger t WHERE t.tgrelid = to_regclass(?) AND t.tgname = ?", reg(o), o.name,
        ) ?: "-- триггер ${o.name} не найден"
        DbObjectKind.CONSTRAINT, DbObjectKind.PRIMARY_KEY, DbObjectKind.FOREIGN_KEY -> one(
            "SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid = to_regclass(?) AND conname = ?", reg(o), o.name,
        )?.let { "ALTER TABLE ${reg(o)} ADD CONSTRAINT ${q(o.name)} $it" } ?: "-- ограничение ${o.name} не найдено"
        else -> "-- DDL для ${o.kind} не поддерживается"
    }

    private fun pgTable(o: DbObject): String {
        val r = reg(o)
        val cols = c.prepareStatement(
            """
            SELECT a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull, pg_get_expr(d.adbin, d.adrelid), a.attidentity::text
            FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = to_regclass(?) AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum
            """.trimIndent(),
        ).use { ps ->
            ps.setString(1, r)
            ps.executeQuery().use { rs ->
                buildList {
                    while (rs.next()) {
                        val sb = StringBuilder("    ${q(rs.getString(1))} ${rs.getString(2)}")
                        when (rs.getString(5)) {
                            "a" -> sb.append(" GENERATED ALWAYS AS IDENTITY")
                            "d" -> sb.append(" GENERATED BY DEFAULT AS IDENTITY")
                            else -> rs.getString(4)?.let { sb.append(" DEFAULT ").append(it) }
                        }
                        if (rs.getBoolean(3)) sb.append(" NOT NULL")
                        add(sb.toString())
                    }
                }
            }
        }
        val constraints = all(
            "SELECT format('    CONSTRAINT %I %s', conname, pg_get_constraintdef(oid)) FROM pg_constraint " +
                "WHERE conrelid = to_regclass(?) ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, conname", r,
        )
        val sb = StringBuilder("CREATE TABLE $r (\n").append((cols + constraints).joinToString(",\n")).append("\n)")
        if (kind == DbKind.CLOUDBERRY) {
            // Cloudberry/Greenplum: политика распределения данных.
            runCatching { one("SELECT pg_get_table_distributedby(to_regclass(?))", r) }.getOrNull()?.let { sb.append("\n").append(it) }
        }
        sb.append(";")
        all(
            "SELECT pg_get_indexdef(i.indexrelid) FROM pg_index i WHERE i.indrelid = to_regclass(?) " +
                "AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid) ORDER BY 1", r,
        ).forEach { sb.append("\n").append(it).append(";") }
        all("SELECT pg_get_triggerdef(oid, true) FROM pg_trigger WHERE tgrelid = to_regclass(?) AND NOT tgisinternal ORDER BY tgname", r)
            .forEach { sb.append("\n").append(it).append(";") }
        one("SELECT obj_description(to_regclass(?), 'pg_class')", r)?.let {
            sb.append("\nCOMMENT ON TABLE $r IS '${it.replace("'", "''")}';")
        }
        return sb.toString()
    }

    private fun pgType(o: DbObject): String {
        val name = "${q(o.schema ?: "public")}.${q(o.name)}"
        return when (o.detail) {
            "enum" -> "CREATE TYPE $name AS ENUM (" + all(
                "SELECT quote_literal(e.enumlabel) FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid JOIN pg_namespace n ON n.oid = t.typnamespace " +
                    "WHERE n.nspname = ? AND t.typname = ? ORDER BY e.enumsortorder", o.schema, o.name,
            ).joinToString(", ") + ")"
            "domain" -> one(
                "SELECT format('CREATE DOMAIN %s AS %s', ?::text, format_type(t.typbasetype, t.typtypmod)) || " +
                    "coalesce(' DEFAULT ' || t.typdefault, '') || CASE WHEN t.typnotnull THEN ' NOT NULL' ELSE '' END || " +
                    "coalesce((SELECT string_agg(' CONSTRAINT ' || quote_ident(c.conname) || ' ' || pg_get_constraintdef(c.oid), '') " +
                    "FROM pg_constraint c WHERE c.contypid = t.oid), '') " +
                    "FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = ? AND t.typname = ?",
                name, o.schema, o.name,
            ) ?: ""
            else -> "CREATE TYPE $name AS (\n" + all(
                "SELECT '    ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod) FROM pg_attribute a " +
                    "JOIN pg_type t ON t.typrelid = a.attrelid JOIN pg_namespace n ON n.oid = t.typnamespace " +
                    "WHERE n.nspname = ? AND t.typname = ? AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum", o.schema, o.name,
            ).joinToString(",\n") + "\n)"
        }
    }

    // ----------------------------------------------------------------------------- ClickHouse

    private fun clickhouse(o: DbObject): String {
        val db = o.schema ?: o.catalog
        return when (o.kind) {
            DbObjectKind.CATALOG, DbObjectKind.SCHEMA -> show("SHOW CREATE DATABASE ${q(o.name)}")
            DbObjectKind.TABLE, DbObjectKind.VIEW -> show("SHOW CREATE TABLE ${q(db!!)}.${q(o.table ?: o.name)}")
            DbObjectKind.FUNCTION -> one("SELECT create_query FROM system.functions WHERE name = ?", o.name) ?: "-- ${o.name}: встроенная функция"
            DbObjectKind.INDEX -> one(
                "SELECT concat('ALTER TABLE ', ?, ' ADD INDEX ', name, ' ', expr, ' TYPE ', type_full, ' GRANULARITY ', toString(granularity)) " +
                    "FROM system.data_skipping_indices WHERE database = ? AND table = ? AND name = ?",
                "${q(db!!)}.${q(o.table!!)}", db, o.table, o.name,
            ) ?: "-- индекс ${o.name} не найден"
            else -> "-- DDL для ${o.kind} не поддерживается"
        }
    }

    private fun show(sql: String): String = c.createStatement().use { st ->
        st.executeQuery(sql).use { rs -> if (rs.next()) rs.getString(1) else "" }
    }

    // ----------------------------------------------------------------------------- Dremio

    private fun dremio(o: DbObject): String = when (o.kind) {
        DbObjectKind.VIEW -> one(
            "SELECT VIEW_DEFINITION FROM INFORMATION_SCHEMA.\"VIEWS\" WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?", o.schema, o.table ?: o.name,
        )?.let { "CREATE OR REPLACE VIEW ${loader.qualified(o)} AS\n$it" } ?: "-- представление не найдено"
        DbObjectKind.TABLE -> "-- Dremio не возвращает DDL таблиц; структура по метаданным:\n-- CREATE TABLE ${loader.qualified(o)} (\n" +
            loader.columns(o).joinToString(",\n") { "--     ${q(it.name)} ${it.detail}" } + "\n-- )"
        else -> "-- DDL для ${o.kind} не поддерживается"
    }
}
